language: node_js
node_js:
  - node
script:
  - npm run lint
  - npm run prettier
notifications:
  email: false
deploy:
  provider: heroku
  api_key: c2a166be-5efe-4f7c-b195-cc5f8f2c45e9
  app: shielded-chamber-99339